//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class VSPackage {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal VSPackage() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSPackage", typeof(VSPackage).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Visual Lua.
    /// </summary>
    internal static string _100 {
        get {
            return ResourceManager.GetString("100", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Integrates Lua language with Visual Studio IDE.
    /// </summary>
    internal static string _102 {
        get {
            return ResourceManager.GetString("102", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Lua.
    /// </summary>
    internal static string _103 {
        get {
            return ResourceManager.GetString("103", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to NOT_IN_SOURCE_DISTRO.
    /// </summary>
    internal static string _110 {
        get {
            return ResourceManager.GetString("110", resourceCulture);
        }
    }
    
    internal static System.Drawing.Icon _400 {
        get {
            object obj = ResourceManager.GetObject("400", resourceCulture);
            return ((System.Drawing.Icon)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Entry Script.
    /// </summary>
    internal static string EntryScript {
        get {
            return ResourceManager.GetString("EntryScript", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Lua Settings.
    /// </summary>
    internal static string GeneralCaption {
        get {
            return ResourceManager.GetString("GeneralCaption", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to LUA_CPATH.
    /// </summary>
    internal static string LUA_CPATH {
        get {
            return ResourceManager.GetString("LUA_CPATH", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to LUA_PATH.
    /// </summary>
    internal static string LUA_PATH {
        get {
            return ResourceManager.GetString("LUA_PATH", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Lua Executable.
    /// </summary>
    internal static string LuaRuntimes {
        get {
            return ResourceManager.GetString("LuaRuntimes", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Lua Environment.
    /// </summary>
    internal static string LuaSettings {
        get {
            return ResourceManager.GetString("LuaSettings", resourceCulture);
        }
    }
}
